version: '3.8'

x-constants:
  db: &dbEnv
    DB_HOST: db
    DB_PORT: 1248
    MYSQL_DATABASE: default
    MYSQL_ROOT_PASSWORD: password
  app: &appEnv
    APP_HOST: app
    APP_PORT: 8080
    DB_HOST: db
    DB_PORT: 1248
    MYSQL_DATABASE: default
    MYSQL_ROOT_PASSWORD: password
    MYSQL_ROOT_USERNAME: root

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      <<: *dbEnv
    volumes:
      - mysql-datavolume:/var/lib/mysql
    ports:
      - '1248:3306'
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:

      <<: *appEnv
    depends_on:
      - db

volumes:
  mysql-datavolume: