version: '3.8'

x-constants:
  db: &dbEnv
    DB_HOST: db
    DB_PORT: 3306
    MYSQL_DATABASE: default
    MYSQL_ROOT_PASSWORD: password
  app: &appEnv
    APP_HOST: app
    APP_PORT: 8080
    DB_HOST: db
    DB_PORT: 1248
    MYSQL_DATABASE: default
    SPRING_DATASOURCE_URL: jdbc:mysql://db:1248/default
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD: password
    SPRING_JPA_HIBERNATE_DDL_AUTO: update

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      <<: *dbEnv
    volumes:
        - mysql-dataVolume:/var/lib/mysql
    ports:
      - '1248:3306'
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    tty: true
    environment:

      <<: *appEnv
    depends_on:
      - db

volumes:
  mysql-dataVolume: